# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(926, 548)
        Form.setStyleSheet("    /*background-color:rgb(220, 220, 220);")
        self.price = QtWidgets.QLabel(Form)
        self.price.setEnabled(True)
        self.price.setGeometry(QtCore.QRect(800, 40, 46, 24))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.price.setFont(font)
        self.price.setObjectName("price")
        self.priceArea = QtWidgets.QTextEdit(Form)
        self.priceArea.setGeometry(QtCore.QRect(750, 240, 159, 61))
        self.priceArea.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    font: 10pt \"宋体\";")
        self.priceArea.setObjectName("priceArea")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(440, 40, 291, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.classify = QtWidgets.QLabel(self.layoutWidget)
        self.classify.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.classify.setFont(font)
        self.classify.setObjectName("classify")
        self.verticalLayout_2.addWidget(self.classify)
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.classifiedArea = QtWidgets.QTableWidget(self.layoutWidget)
        self.classifiedArea.setStyleSheet("#classifiedArea{\n"
"    border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    /*gridline-color:rgb(255, 255, 255);*/\n"
"}/*\n"
"QtableView{\n"
"    border:none;\n"
"}\n"
"QtableView::item{\n"
"    border:none;\n"
"    border-right:none;\n"
"    border-buttom:none;\n"
"}*/\n"
"\n"
"QHeaderView::section, QTableCornerButton::section {\n"
"    padding: 1px;\n"
"    border:none;\n"
"     border: 2px groove white;\n"
"    border-radius: 6px;  \n"
"     border: 2px groove white;\n"
"    /*border-bottom: 1px solid rgb(75, 120, 154);\n"
"    border-right: 1px solid rgb(75, 120, 154);\n"
"    border-bottom: 1px solid gray;\n"
"    background-color:rgba(75, 120, 154, 1);\n"
"    color:rgba(126,206,244,1);*/\n"
"}")
        self.classifiedArea.setObjectName("classifiedArea")
        self.classifiedArea.setColumnCount(2)
        self.classifiedArea.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        item.setFont(font)
        self.classifiedArea.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        item.setFont(font)
        self.classifiedArea.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        item.setFont(font)
        self.classifiedArea.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        item.setFont(font)
        self.classifiedArea.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        item.setFont(font)
        self.classifiedArea.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        item.setFont(font)
        self.classifiedArea.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        item.setFont(font)
        self.classifiedArea.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        item.setFont(font)
        self.classifiedArea.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        item.setFont(font)
        self.classifiedArea.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.classifiedArea.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/kind.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/image/kind.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.classifiedArea.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/price1.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon1)
        self.classifiedArea.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.classifiedArea)
        self.priceButton_2 = QtWidgets.QPushButton(Form)
        self.priceButton_2.setGeometry(QtCore.QRect(770, 480, 121, 41))
        self.priceButton_2.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    background-color:rgb(229, 229, 229);")
        self.priceButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/Clear-1.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.priceButton_2.setIcon(icon2)
        self.priceButton_2.setObjectName("priceButton_2")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(21, 41, 391, 481))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.article = QtWidgets.QLabel(self.layoutWidget1)
        self.article.setEnabled(True)
        self.article.setMaximumSize(QtCore.QSize(290, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.article.setFont(font)
        self.article.setStyleSheet("")
        self.article.setObjectName("article")
        self.verticalLayout.addWidget(self.article)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.price.setText(_translate("Form", "总价"))
        self.classify.setText(_translate("Form", "分类"))
        item = self.classifiedArea.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.classifiedArea.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.classifiedArea.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.classifiedArea.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.classifiedArea.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.classifiedArea.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.classifiedArea.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.classifiedArea.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.classifiedArea.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.classifiedArea.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.classifiedArea.horizontalHeaderItem(0)
        item.setText(_translate("Form", "种类"))
        item = self.classifiedArea.horizontalHeaderItem(1)
        item.setText(_translate("Form", "价格"))
        self.article.setText(_translate("Form", "物品"))
import ui.image1_rc
